- name: ixa_tok
  input: 
  output: 
  - text
  cmd: ixa-tok
- name: alpino
  input:
  - text
  output: 
  - terms
  - deps
  - constituents
  cmd: alpino
- name: ixa_nerc
  input:
  - text
  - terms
  output: 
  - entities
  cmd: ixa-nerc
- name: ixa_time
  input:
  - text
  - terms
  output: 
  - timeExpressions
  cmd: time
- name: vua_wsd
  input:
  - text
  - terms
  output: 
  - terms
  cmd: svm-wsd
- name: vua_srl
  input:
  - terms
  - constituents
  - deps
  output: 
  - srl
  cmd: srl
- name: pm_tagger
  input:
  - terms
  output: 
  - terms
  cmd: pm-tag
  after: 
  - vua_wsd
- name: nom_event
  input:
  - text
  - terms
  output: 
  - srl
  cmd: nom-ev
  after: 
  - vua_wsd
  - pm_tagger
- name: nom_pred
  input:
  - terms
  - deps
  - srl
  output: 
  - srl
  cmd: np-srl
  after: 
  - nom_event
- name: f_net
  input:
  - terms
  - srl
  output: 
  - srl
  cmd: fnet
  after: 
  - pm_tagger
  - vua_wsd
  - vua_srl
- name: coref
  input:
  - srl
  output: 
  - coreferences
  cmd: coref
  after: 
  - vua_srl
  - nom_pred
- name: opin
  input:
  - text
  - terms
  - constituents
  - deps
  - entities
  output: 
  - opinions
  cmd: opin
- name: fact
  input:
  - terms
  - opinions
  - coreferences
  output: 
  - factualities
  cmd: fact
