- name: ixa-pipe-tok
  input: 
  output: 
  - text
  cmd: ixa-pipe-tok.sh
- name: vua-alpino
  input:
  - text
  output: 
  - terms
  - deps
  - constituents
  cmd: vua-alpino.sh
- name: ixa-pipe-nerc
  input:
  - text
  - terms
  output: 
  - entities
  cmd: ixa-pipe-nerc.sh
- name: vua-heideltime
  input:
  - text
  - terms
  output: 
  - timeExpressions
  cmd: vua-heideltime.sh
- name: vua-wsd
  input:
  - text
  - terms
  output: 
  - terms
  cmd: vua-wsd.sh
- name: vua-srl
  input:
  - terms
  - constituents
  - deps
  output: 
  - srl
  cmd: vua-srl.sh
- name: vua-ontotagging
  input:
  - terms
  output: 
  - terms
  cmd: vua-ontotagging.sh
  after: 
  - vua-wsd
- name: vua-nominal-event-detection
  input:
  - text
  - terms
  output: 
  - srl
  cmd: vua-nominal-event-detection.sh
  after: 
  - vua-wsd
  - vua-ontotagging
- name: vua-srl-dutch-nominal-events
  input:
  - terms
  - deps
  - srl
  output: 
  - srl
  cmd: vua-srl-dutch-nominal-events.sh
  after: 
  - vua-nominal-event-detection
- name: vua-framenet-classifier
  input:
  - terms
  - srl
  output: 
  - srl
  cmd: vua-framenet-classifier.sh
  after: 
  - vua-ontotagging
  - vua-wsd
  - vua-srl
- name: vua-eventcoreference
  input:
  - srl
  output: 
  - coreferences
  cmd: vua-eventcoreference
  after: 
  - vua-srl
  - vua-srl-dutch-nominal-events
- name: opinion-miner
  input:
  - text
  - terms
  - constituents
  - deps
  - entities
  output: 
  - opinions
  cmd: opinion-miner.sh
- name: multilingual-factuality
  input:
  - terms
  - opinions
  - coreferences
  output: 
  - factualities
  cmd: multilingual-factuality.sh
